CREATE TABLE tracklist (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    soundfile TEXT NOT NULL,
    onboxes INTEGER [],
    ref INTEGER
        REFERENCES patterns(pattern_ref) ON DELETE CASCADE NOT NULL
);